WebScout/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('WebScoutApp.urls')),
]

WebScoutApp/urls.py
from django.contrib import admin
from django.urls import path, include
from WebScoutApp import views
from django.conf import settings
from django.conf.urls.static import static

app_name='home'

urlpatterns = [
    #path('contact', views.contact, name='contact'),
    path('', views.home, name='home'),
    path('scrape', views.scrape, name='scrape'),
    #path('report', views.report, name='report'),
    path('report/<str:collection_name>/', views.report, name='report'),
    path('export_pdf/', views.export_pdf, name='export_pdf'),
    path('list_db', views.list_db, name='list_db'),
    
    #path('about', views.about, name='about'),
]

templates/db_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MongoDB Collections</title>
    <!-- Include Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <style>
        /* Reset default margin and padding */
        * {
            margin: 0;
            padding: 0;
        }

        /* Global styles */
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
        }

        .content-container-new {
            max-width: 800px;
            margin: 70px auto 20px;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
            border-radius: 5px;
        }

        h1 {
            text-align: center;
            color: #333;
        }

        ul {
            list-style: none;
            padding: 0;
        }

        li {
            margin: 10px 0;
            padding: 10px;
            background-color: #f9f9f9;
            border: 1px solid #ddd;
            border-radius: 5px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        a {
            text-decoration: none;
            color: #007BFF;
            font-weight: bold;
        }

        /* Navbar styles */
        .navbar-container {
            background-color: #e3f2fd;
        }

        /* Footer styles */
        .footer {
            background-color: #343a40;
            color: #fff;
            text-align: center;
            padding: 10px 0;
            margin-top: 20px;
        }
    </style>
</head>

<body>
    <header>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="#">Web Scout</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="/">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
   
    <div class="content-container-new">
        <h1>MongoDB Collections</h1>
        <ul>
            {% for collection_name in collection_names %}
                <li>
                    <span>{{ collection_name }}</span>
                    <a href="{% url 'home:report' collection_name=collection_name %}">View</a>
                </li>
            {% endfor %}
        </ul>
    </div>

    <!-- Footer -->
    <footer class="footer">
        <div class="container">
            &copy; {{ year }} Web Scout
        </div>
    </footer>

    <!-- Include Bootstrap JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
</body>
</html>

templates/report.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detailed Report - {{ collection_name }}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <style>
        /* Add your custom CSS styles here */

        /* Center align h1 headings */
        h1 {
            text-align: center;
        }

        /* Add spacing between sections */
        .section {
            margin-bottom: 30px;
        }

        /* Style the list of top-rated books */
        .top-rated-books ul {
            list-style: none;
            padding: 0;
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
        }

        .top-rated-books li {
            flex: 0 0 calc(33.33% - 20px);
            margin: 10px;
            padding: 15px;
            border: 1px solid #ccc;
            border-radius: 5px;
            text-align: center;
        }

        /* Style the footer */
        .footer {
            background-color: #343a40;
            color: #fff;
            text-align: center;
            padding: 10px 0;
        }
    </style>
</head>
<body>
    <header>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="/">Web Scout</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="/">Home</a>
                        </li>
                        
                        <a href="{% url 'home:export_pdf' %}" class="btn btn-outline-primary">Download Report</a>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <!-- Price Distribution Report -->
        <h1>{{ collection_name }} - Detailed Report</h1> <br><br><br>
        <div class="section">
            <h1>Price Distribution Report</h1>
            <div>{{ plot_div|safe }}</div>
        </div>
        
        <!-- In Stock Report -->
        <div class="section">
            <h1>In Stock Report</h1>
            <div>{{ chart_div_2|safe }}</div>
        </div>
        
        <!-- Price vs Rating Report -->
        <div class="section">
            <h1>Price vs Rating Report</h1>
            <div>{{ chart_div_3|safe }}</div>
        </div>
        
        <!-- Top-Rated Books -->
        <div class="section top-rated-books">
            <h1>Top-Rated Books</h1>
            <ul>
                {% for book in top_rated_books %}
                    <li>
                        <img src="{{ book.Image_Url }}" alt="{{ book.Title }}" width="100" height="150">
                        <p><strong>Title:</strong> {{ book.Title }}</p>
                        <p><strong>Rating:</strong> {{ book.Rating }}/5</p>
                        <p><strong>Price:</strong> {{ book.Price }}</p>
                        <p><strong>In Stock:</strong> {{ book.inStock }}</p>
                    </li>
                {% endfor %}
            </ul>
        </div>
        
        <!-- Word Cloud for Book Titles -->
        <div class="section">
            <h2>Word Cloud for Book Titles</h2>
            <div>
                <img src="data:image/png;base64,{{ wordcloud_image }}" alt="Word Cloud">
            </div>
        </div>
    </div>

    <!-- Footer -->
    <footer class="footer">
        <div class="container">
            &copy; {{ year }} Web Scout
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
</body>
</html>